In [1]:
import pandas as pd
import numpy as np

# Load CSV Files

In [2]:
dataset1 = pd.read_csv("dataset/Challenger_Ranked_Games.csv")
dataset2 = pd.read_csv("dataset/GrandMaster_Ranked_Games.csv")
dataset3 = pd.read_csv("dataset/Master_Ranked_Games.csv")

# Combine CSV Files

In [3]:
#dataset = dataset1.append(dataset2)
#dataset = dataset.append(dataset3)

In [4]:
#dataset.reset_index(drop=True)

In [5]:
mergeddataset = pd.concat([dataset1,dataset2,dataset3])

In [6]:
mergeddataset.reset_index(drop=True)

,gameId,gameDuraton,blueWins,blueFirstBlood,blueFirstTower,blueFirstBaron,blueFirstDragon,blueFirstInhibitor,blueDragonKills,blueBaronKills,...,redAssist,redChampionDamageDealt,redTotalGold,redTotalMinionKills,redTotalLevel,redAvgLevel,redJungleMinionKills,redKillingSpree,redTotalHeal,redObjectDamageDealt
0,4247263043,1323,0,1,0,0,0,0,0,0,...,68,73016,49832,533,64,12.8,138,8,38711,60463
1,4247155821,1317,1,0,0,0,1,0,2,0,...,8,44218,37136,571,59,11.8,134,3,24829,14105
2,4243963257,932,0,0,0,0,0,0,0,0,...,20,30797,35364,400,50,10.0,89,5,12589,45201
3,4241678498,2098,0,0,0,1,1,0,1,1,...,72,125866,70528,832,84,16.8,205,9,65312,88202
4,4241538868,2344,1,1,1,1,1,1,2,2,...,83,131536,74596,794,85,17.0,227,7,86431,64141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199920,4216107910,2479,1,1,0,0,0,0,3,1,...,41,149798,72167,789,86,17.2,258,6,34890,62124
199921,4031558534,932,0,0,0,0,0,0,0,0,...,26,37534,32931,364,51,10.2,110,5,11983,31400
199922,3882136458,2081,0,1,1,0,0,0,1,0,...,68,97369,71576,797,85,17.0,222,8,33499,79612
199923,4137464714,1619,0,0,0,0,0,0,1,0,...,68,116262,59001,524,72,14.4,162,11,52292,60903
199924,4195660684,1129,1,0,1,0,0,1,1,0,...,4,33263,26963,423,47,9.4,71,1,12749,8035

We will Delete games which is less than 300 seconds.

In [7]:
mergeddataset = mergeddataset[~(mergeddataset["gameDuraton"] <300)]

In [8]:
mergeddataset

,gameId,gameDuraton,blueWins,blueFirstBlood,blueFirstTower,blueFirstBaron,blueFirstDragon,blueFirstInhibitor,blueDragonKills,blueBaronKills,...,redAssist,redChampionDamageDealt,redTotalGold,redTotalMinionKills,redTotalLevel,redAvgLevel,redJungleMinionKills,redKillingSpree,redTotalHeal,redObjectDamageDealt
0,4247263043,1323,0,1,0,0,0,0,0,0,...,68,73016,49832,533,64,12.8,138,8,38711,60463
1,4247155821,1317,1,0,0,0,1,0,2,0,...,8,44218,37136,571,59,11.8,134,3,24829,14105
2,4243963257,932,0,0,0,0,0,0,0,0,...,20,30797,35364,400,50,10.0,89,5,12589,45201
3,4241678498,2098,0,0,0,1,1,0,1,1,...,72,125866,70528,832,84,16.8,205,9,65312,88202
4,4241538868,2344,1,1,1,1,1,1,2,2,...,83,131536,74596,794,85,17.0,227,7,86431,64141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107120,4216107910,2479,1,1,0,0,0,0,3,1,...,41,149798,72167,789,86,17.2,258,6,34890,62124
107121,4031558534,932,0,0,0,0,0,0,0,0,...,26,37534,32931,364,51,10.2,110,5,11983,31400
107122,3882136458,2081,0,1,1,0,0,0,1,0,...,68,97369,71576,797,85,17.0,222,8,33499,79612
107123,4137464714,1619,0,0,0,0,0,0,1,0,...,68,116262,59001,524,72,14.4,162,11,52292,60903
107124,4195660684,1129,1,0,1,0,0,1,1,0,...,4,33263,26963,423,47,9.4,71,1,12749,8035

gameId Deleted

In [9]:
del mergeddataset['gameId']

In [10]:
from sklearn import preprocessing

x = mergeddataset.values
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
preprocesseddataset = pd.DataFrame(x_scaled, columns=mergeddataset.columns)

In [11]:
preprocesseddataset

,gameDuraton,blueWins,blueFirstBlood,blueFirstTower,blueFirstBaron,blueFirstDragon,blueFirstInhibitor,blueDragonKills,blueBaronKills,blueTowerKills,...,redAssist,redChampionDamageDealt,redTotalGold,redTotalMinionKills,redTotalLevel,redAvgLevel,redJungleMinionKills,redKillingSpree,redTotalHeal,redObjectDamageDealt
0,0.295020,0.0,1.0,0.0,0.0,0.0,0.0,0.000000,0.00,0.000000,...,0.296943,0.203283,0.351692,0.369369,0.441379,0.441379,0.282787,0.275862,0.187229,0.306709
1,0.293283,1.0,0.0,0.0,0.0,1.0,0.0,0.285714,0.00,0.363636,...,0.034934,0.123107,0.262090,0.395703,0.406897,0.406897,0.274590,0.103448,0.120087,0.071550
2,0.181818,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.00,0.000000,...,0.087336,0.085742,0.249584,0.277200,0.344828,0.344828,0.182377,0.172414,0.060888,0.229290
3,0.519398,0.0,0.0,0.0,1.0,1.0,0.0,0.142857,0.25,0.181818,...,0.314410,0.350422,0.497756,0.576577,0.579310,0.579310,0.420082,0.310345,0.315886,0.447419
4,0.590620,1.0,1.0,1.0,1.0,1.0,1.0,0.285714,0.50,1.000000,...,0.362445,0.366208,0.526466,0.550243,0.586207,0.586207,0.465164,0.241379,0.418030,0.325366
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197602,0.629705,1.0,1.0,0.0,0.0,0.0,0.0,0.428571,0.25,0.636364,...,0.179039,0.417051,0.509323,0.546778,0.593103,0.593103,0.528689,0.206897,0.168748,0.315134
197603,0.181818,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.00,0.000000,...,0.113537,0.104498,0.232413,0.252252,0.351724,0.351724,0.225410,0.172414,0.057957,0.159282
197604,0.514476,0.0,1.0,1.0,0.0,0.0,0.0,0.142857,0.00,0.545455,...,0.296943,0.271084,0.505152,0.552322,0.586207,0.586207,0.454918,0.275862,0.162020,0.403845
197605,0.380718,0.0,0.0,0.0,0.0,0.0,0.0,0.142857,0.00,0.181818,...,0.296943,0.323684,0.416403,0.363132,0.496552,0.496552,0.331967,0.379310,0.252914,0.308941
197606,0.238854,1.0,0.0,1.0,0.0,0.0,1.0,0.142857,0.00,0.545455,...,0.017467,0.092607,0.190293,0.293139,0.324138,0.324138,0.145492,0.034483,0.061661,0.040759